version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kaio
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres-node
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: clean-node
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/app
    links:
      - database_ignite
    depends_on:
      - database_ignite
volumes:
  pgdata:
    driver: local
